name: xlmr_es
description: XLM-RoBERTa multilingual model for Spanish NER
engine: transformers
model: xlm-roberta-large-finetuned-conll03-english
language: es

# Filter predictions below this confidence score (0-1)
score_threshold: 0.5

recognizers:
  - transformers
